# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "juve-xx"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "ICL": 
        filters: ["In Context Learning", "ICL","Transformer", "Algorithm"]
    "Transformer":
        filters: ["Transformer", "Self Attention", "Algorithm","Linear", "Single"]
    "Optimization":
        filters: ["Optimization", "Gradient Descent"]
    "Over paramterized":
        filters: ["Over Parameterized"]
    "Machine Learning":
        filters: ["Loss landscape", "Machine Leanring Theory", "Gradient Descent"]
    "Reinforcement":
        filters: ["Reinforcement learning"]
